name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '14 14 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        with:
          packages: pdftk-java
          version: 1.1
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install and run
        env:
          DOCUMENT_CLOUD_USERNAME: '${{ secrets.DOCUMENT_CLOUD_USERNAME }}'
          DOCUMENT_CLOUD_PASSWORD: '${{ secrets.DOCUMENT_CLOUD_PASSWORD }}'
          PDFTK_PATH: 'pdftk.pdftk-java'
        run: |-
          npm install
          npm run scrape
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
